import type { Metadata } from "next";
import { Yeseva_One, Work_Sans } from "next/font/google";
import "./globals.css";

const yesevaOne = Yeseva_One({
  variable: "--font-yeseva-one",
  subsets: ["latin"],
  weight: ["400"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${yesevaOne.variable} ${workSans.variable} antialiased relative`}
      >
        {children}
      </body>
    </html>
  );
}
